server {
    listen 80;
    server_name _;

    # Frontend — React сайт
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
    }

    # Backend API
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 10M;
    }

    # Статические файлы (фото зала славы и др.)
    location /static/ {
        proxy_pass http://backend:8000/static/;
        proxy_set_header Host $host;
    }

    # Файлы соревнований — принудительное скачивание
    location /static/competition-files/ {
        proxy_pass http://backend:8000/static/competition-files/;
        proxy_set_header Host $host;
        add_header Content-Disposition 'attachment';
    }

    # Swagger документация
    location /docs {
        proxy_pass http://backend:8000/docs;
    }
}
